import PureCloudPlatformClientV2
from PureCloudPlatformClientV2.rest import ApiException
from pprint import pprint

# Configure OAuth2 access token for authorization: PureCloud OAuth
PureCloudPlatformClientV2.configuration.access_token = 'your_access_token'
# or use get_client_credentials_token(...), get_saml2bearer_token(...), get_code_authorization_token(...) or get_pkce_token(...)

# create an instance of the API class
api_instance = PureCloudPlatformClientV2.UsersApi();
authority_name = 'authority_name_example' # str | Authority Name
external_key = 'external_key_example' # str | External Key
expand = ['expand_example'] # list[str] | Which fields, if any, to expand (optional)

try:
    # Get the user associated with external identifier.
    api_response = api_instance.get_users_externalid_authority_name_external_key(authority_name, external_key, expand=expand)
    pprint(api_response)
except ApiException as e:
    print("Exception when calling UsersApi->get_users_externalid_authority_name_external_key: %s\n" % e)