import PureCloudPlatformClientV2
from PureCloudPlatformClientV2.rest import ApiException
from pprint import pprint

# Configure OAuth2 access token for authorization: PureCloud OAuth
PureCloudPlatformClientV2.configuration.access_token = 'your_access_token'
# or use get_client_credentials_token(...), get_saml2bearer_token(...), get_code_authorization_token(...) or get_pkce_token(...)

# create an instance of the API class
api_instance = PureCloudPlatformClientV2.WorkforceManagementApi();
management_unit_id = 'management_unit_id_example' # str | The ID of the management unit, or 'mine' for the management unit of the logged-in user.
work_plan_id = 'work_plan_id_example' # str | The ID of the work plan to update
validation_mode = 'validation_mode_example' # str | Allows to update work plan even if validation result is invalid (optional)
body = PureCloudPlatformClientV2.WorkPlan() # WorkPlan | body (optional)

try:
    # Update a work plan
    api_response = api_instance.patch_workforcemanagement_managementunit_workplan(management_unit_id, work_plan_id, validation_mode=validation_mode, body=body)
    pprint(api_response)
except ApiException as e:
    print("Exception when calling WorkforceManagementApi->patch_workforcemanagement_managementunit_workplan: %s\n" % e)