import PureCloudPlatformClientV2
from PureCloudPlatformClientV2.rest import ApiException
from pprint import pprint

# Configure OAuth2 access token for authorization: PureCloud OAuth
PureCloudPlatformClientV2.configuration.access_token = 'your_access_token'
# or use get_client_credentials_token(...), get_saml2bearer_token(...), get_code_authorization_token(...) or get_pkce_token(...)

# create an instance of the API class
api_instance = PureCloudPlatformClientV2.UsersApi();
user_id = 'user_id_example' # str | User ID
verifier_id = 'verifier_id_example' # str | Verifier ID
body = PureCloudPlatformClientV2.UpdateVerifierRequest() # UpdateVerifierRequest | Verifier Update

try:
    # Update a verifier
    api_response = api_instance.put_user_verifier(user_id, verifier_id, body)
    pprint(api_response)
except ApiException as e:
    print("Exception when calling UsersApi->put_user_verifier: %s\n" % e)